AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DNS Domain Management

Parameters:
  RootDomainName:
    Type: String
    Description: Root domain name

Resources:
  DnsRootDomain:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/dns-zone/template.yaml"
      Parameters:
        RootDomainName: !Ref RootDomainName

  DnsCfnCr:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./stacks/cfn-cr/template.yaml"
#      Parameters:
#        DnsRootZoneId: !GetAtt DnsRootDomain.Outputs.HostedZoneId