name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup job workspace
        uses: ServerlessOpsIO/gha-setup-workspace@v2

      - name: Setup Python environment
        uses: ServerlessOpsIO/gha-setup-python@v1
        with:
          python_version: 3.12

      - name: Assume AWS Credentials
        uses: ServerlessOpsIO/gha-assume-aws-credentials@v1
        with:
          build_aws_account_id: ${{ secrets.AWS_CICD_ACCOUNT_ID }}

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2

      # FIXME: We're only validating the top-level template and not the rest.
      - name: Validate SAM template
        run: sam validate --lint -t template.yaml

      - name: Validate StackSets SAM template (DNS Zone)
        run: sam validate --lint -t stacks/dns-zone/template.yaml

      - name: Validate StackSets SAM template (CFN CR)
        run: sam validate --lint -t stacks/cfn-cr/template.yaml

      - name: Unit tests
        id: unit-tests
        shell: bash
        run: pipenv run pytest

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Store Artifacts
        uses: ServerlessOpsIO/gha-store-artifacts@v2
        with:
          use_aws_sam: true


  deploy_stacksets:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup job workspace
        uses: ServerlessOpsIO/gha-setup-workspace@v2
        with:
          checkout_artifact: true

      - name: Assume AWS Credentials
        uses: ServerlessOpsIO/gha-assume-aws-credentials@v1
        with:
          build_aws_account_id: ${{ secrets.AWS_CICD_ACCOUNT_ID }}
          deploy_aws_account_id: ${{ secrets.DEPLOYMENT_ACCOUNT_ID }}

      - name: Deploy via AWS SAM
        uses: ServerlessOpsIO/gha-deploy-aws-sam@v1
        with:
          aws_account_id: ${{ secrets.DEPLOYMENT_ACCOUNT_ID }}
          template_file: packaged-template.yaml
          env_json: ${{ toJson(env) }}
          secrets_json: ${{ toJson(secrets) }}